// Mocks generated by Mockito 5.4.4 from annotations
// in Steamy/test/edit_account_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:Steamy/services/api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get getBaseUrl => (super.noSuchMethod(
        Invocation.getter(#getBaseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#getBaseUrl),
        ),
      ) as String);

  @override
  _i4.Future<bool> ensureLoggedIn(dynamic context) => (super.noSuchMethod(
        Invocation.method(
          #ensureLoggedIn,
          [context],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> registerUser(
    String? email,
    String? password,
    String? displayName, {
    String? bio,
    String? preferences,
    double? locationLat,
    double? locationLon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [
            email,
            password,
            displayName,
          ],
          {
            #bio: bio,
            #preferences: preferences,
            #locationLat: locationLat,
            #locationLon: locationLon,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> loginUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchMatches() => (super.noSuchMethod(
        Invocation.method(
          #fetchMatches,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> sendMatchRequest(String? matchedId) => (super.noSuchMethod(
        Invocation.method(
          #sendMatchRequest,
          [matchedId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchNextMatch(
          List<Map<String, dynamic>>? excludedMatches) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNextMatch,
          [excludedMatches],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> sendChatMessage(
    int? receiverId,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendChatMessage,
          [
            receiverId,
            text,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchChatMessages(int? userId2) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChatMessages,
          [userId2],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> updateProfile(
    int? id, {
    String? email,
    String? displayName,
    String? bio,
    String? profilePic,
    double? locationLat,
    double? locationLon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [id],
          {
            #email: email,
            #displayName: displayName,
            #bio: bio,
            #profilePic: profilePic,
            #locationLat: locationLat,
            #locationLon: locationLon,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getUserProfile(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [id],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
